name = "note-chord-soulciety"
compatibility_date = "2024-09-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "note-chord-soulciety"
database_id = "9adc6f93-db09-4a97-91dd-e5ab42eed1ec"
